name: ESLINT Linter

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Installing Node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Installing Dependencies
        run: npm install

      - name: Executing Linter
        run: npm run lint
